#image:
#  file: .gitpod.docker

tasks:
  #prepare env
  #- init:
  #- name: add direnv
  #  command: direnv allow
  - name: run tailscaled
    command:  sudo tailscaled
  - name: run tailscale
    #command: sudo -E tailscale up --authkey "${TAILSCALE_AUTHKEY}" --hostname "${GITPOD_WORKSPACE_ID}" --accept-dns --exit-node "${EXIT_NODE}"
    command: sudo -E tailscale up --authkey "${TAILSCALE_AUTHKEY}" --hostname "${GITPOD_WORKSPACE_ID}"

