image:
  file: .gitpod.docker

tasks:
  #prepare env
  - init:
  - name: add direnv
    command: direnv allow
  - name: run tailscaled
    command:  sudo tailscaled
  - name: run tailscale
    command: tailscale up --authkey "${TAILSCALE_AUTHKEY}" --hostname "${FITPOD_WORKSPACE_ID}" --accept-dns --exit-node "${EXIT_NODE}}"

